ALTER TABLE tickets
  ADD COLUMN ext_json JSON NULL COMMENT '场景特有字段',
  ADD COLUMN order_prefix VARCHAR(8) NOT NULL DEFAULT '' COMMENT '编号前缀(12/13/29/30/42)',
  ADD COLUMN biz_type VARCHAR(64) NOT NULL DEFAULT '' COMMENT '业务类型',
  ADD COLUMN biz_sub_type VARCHAR(64) NOT NULL DEFAULT '' COMMENT '业务细分类型',
  ADD COLUMN deadline DATETIME NULL COMMENT '规定回件日期(SLA)',
  ADD COLUMN receive_unit VARCHAR(64) NOT NULL DEFAULT '' COMMENT '接单单位',
  ADD COLUMN need_reply TINYINT NOT NULL DEFAULT 1 COMMENT '是否需要回复';
